label var IQ_factor 			"Standardized IQ score"
label var likeSchool			"Likes school"
label var childBMI 				"BMI"
label var childSDQ_score		"SDQ reported by parents"
label var RiskSuspended 		"Ever suspended from school"
label var Cig 					"Number of cigarettes per day"
label var sport 				"Days exercise per week"
label var BMI 					"BMI"
label var LocusControl 			"Locus of control"
label var SDQ_score				"Strengths-difficulties score (SDQ)"
label var Depression_score		"Depression score"
label var votoMaturita 			"High School grades"
label var votoUni 				"University grades"
label var highschoolGrad 		"High school graduate"
label var PA_Empl 				"Employed"
label var Maria 				"Ever used marijuana"
label var Smoke 				"Smoking indicator"
label var childSickDays			"Num. times unhealthy in last 30 days"
label var SickDays 				"Num. times unhealthy in last 30 days"
label var Reddito_1				"Income: 5,000 euros or less"
label var Reddito_2				"Income: 5,001-10,000 euros"
label var Reddito_3 			"Income: 10,001-25,000 euros"
label var Reddito_4 			"Income: 25,001-50,000 euros"
label var Reddito_5 			"Income: 50,001-100,000 euros"
label var Reddito_6 			"Income: 100,001-250,000 euros"
label var Reddito_7 			"Income: more than 250,000 euros"	
label var HrsTot				"Hours worked per week"
label var SES_self				"Self-employed indicator"
